### ISSUE TITLE
City and state should be in address request(?).

### ISSUE THREAD

**Issue by kyle-arkade** [omneo/omneo-sdk#2]
Should address_line_1, city, state, postcode and country be address request attributes?

Addresses also have meta I believe.

https://github.com/omneo/omneo-sdk/blob/97b803b424e8ff731ef6e7127ae16eade20cc521/src/types.ts#L45

**Comment by oliverarkade** [comment]
Yep, there are some fields that are required for the API Request which are different from the Response
I've updated the types to be the correct required fields
